//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDoor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AndroidDevice
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string SmartDoorDeviceId { get; set; }
        public string UserId { get; set; }
        public string Privilege { get; set; }
        public string RoomId { get; set; }
    }
}
