//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;

namespace SmartDoor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoorDeviceModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string AndroidDeviceId { get; set; }
        public string UserId { get; set; }
        public string Privilege { get; set; }
        public string RoomId { get; set; }
        public bool Active { get; set; }
    }

    public class DoorDeviceDbContext : DbContext
    {
        public DoorDeviceDbContext() : base("DefaultConnection") {}
        public DbSet<DoorDeviceModel> DoorDevices { get; set; }
    }

}
