//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDoor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string SmartDoorDeviceId { get; set; }
        public byte[] File { get; set; }
        public string UserId { get; set; }
    }
}
